### ISSUE TITLE
Enabling Multi-GPU Support for SDXL for WebUI

### ISSUE THREAD

**Issue by linkedlist771** [TonyLianLong/stable-diffusion-xl-demo#1]
Enabling Multi-GPU Support for SDXL

Dear developer,

I am currently using the SDXL for my project, and I am encountering some difficulties with enabling multi-GPU support. I have four Nvidia 3090 GPUs at my disposal, but so far, I have only been able to run the software on one of them, running such a large model on a single 3090 is very slow and ram cosuming.

My attempts to distribute the workload among all GPUs have been unsuccessful. These have included:

- Attempt : Use the accelerate to config the multi GPUS and run.

Unfortunately, these methods have not resulted in successful multi-GPU utilization.

For your reference, here is some information about my setup:

- Operating System: Ubuntu
- Python Version: 3.10.12
- CUDA Version:12.2
- Deep Learning Framework: PyTorch 2.0.1

I'm not sure if I'm missing something or if there's an issue with SDXL itself. Therefore, I'm writing to ask if you could provide some guidance on this matter. Is there a built-in way to enable multi-GPU support, or are there any additional steps that I might have overlooked? Thank you!

**Comment by TonyLianLong** [comment]
Just added a `MULTI_GPU` option that can be enabled with setting environment variable. This performs data parallelism.

On a server with 4 GPUs, you can see high GPU utilization.

<img width="1008" alt="image" src="https://github.com/TonyLianLong/stable-diffusion-xl-demo/assets/1451234/0d93c387-9558-49da-930e-4bf926ca609d">

Further acceleration can be implemented by moving the model duplicate from forward to init in DataParallel class, but the current version already achieves significant speed-up in my setting with minimal code changes.
