### ISSUE TITLE
CUDA Usage is 0%

### ISSUE THREAD

**Issue by densechen** [TonyLianLong/stable-diffusion-xl-demo#5]
<img width="703" alt="image" src="https://github.com/TonyLianLong/stable-diffusion-xl-demo/assets/14089191/f4224e15-269d-4edc-acb5-8b11a2b001a1">

```shell
PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:512 SDXL_MODEL_DIR=pretrained_models OFFLOAD_BASE=false OFFLOAD_REFINER=false  python 
app.py
```

**Comment by TonyLianLong** [comment]
Are you able to generate anything? When you're not generating, the utility will be 0. Also it seems like there are processes using your GPU (taking GPU memory).

**Comment by densechen** [comment]
I find that after I click submit button on a webpage, the infer function does not run.

**Comment by TonyLianLong** [comment]
Interesting, did you use the public or local link? If you use the local link, it seems like inference runs right after clicking the button on my side.

**Comment by densechen** [comment]
I run it on a server local port and transfer it to my computer.&nbsp;More specifically, after I click the submit button, the webpage is going into pending for processing result. But the server backend never go into the infer function.
I think it this the gradio or chrome version issue, which make it fail to parse the webpage correctly?
&nbsp;


Dense&nbsp;Chen
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Long(Tony) ***@***.***&gt;; 
发送时间: 2023年8月17日(星期四) 凌晨0:25
收件人: ***@***.***&gt;; 
抄送: "Dense ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [TonyLianLong/stable-diffusion-xl-demo] CUDA Usage is 0% (Issue #5)





 
Interesting, did you use the public or local link? If you use the local link, it seems like inference runs right after clicking the button on my side.
 
&mdash;

**Comment by TonyLianLong** [comment]
I guess you could try to upgrade gradio and your browser. You could also add a print statement in the inference function to see whether it's called. If it's not, I suggest submitting an issue to gradio maintainers.

**Comment by TonyLianLong** [comment]
I upgraded gradio in requirements.txt. Could you try to install the requirements and see if it works? It works on Colab on my end (just tested).

**Comment by densechen** [comment]
@TonyLianLong It works after I upgrade gradio from 3.11 to 3.14
